### PR TITLE
feat: remove annotations when converting tests

### LINKED ISSUE #8: [2.x] Remove "annotations"
I think would be cool to remove annotations when migrating tests to Pest. As example:

```php
<?php

namespace Tests\Feature;

// use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     */
    public function test_the_application_returns_a_successful_response(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
```

Should be converted to:
```php
<?php

uses(Tests\TestCase::class);

test('the application returns a successful response', function () {
    $response = $this->get('/');

    $response->assertStatus(200);
});
```

### PR DESCRIPTION
**Pull request by mandisma**
Resolves #8

### CODE REVIEW

**Comment by schonhoff** [comment]
Hi,

wouldn't this remove the entire comment even if there are `@group` tags? See: https://github.com/pestphp/pest-plugin-drift/issues/16

**Comment by mandisma** [comment]
Hi,

Yes this will remove the entire comment. The group tag key needs to be converted.
I will open a PR that will handle this.

Thanks for the feedback.

**Comment by nunomaduro** [comment]
Can you address the conflicts?

**Comment by schonhoff** [comment]
> Hi,
> 
> Yes this will remove the entire comment. The group tag key needs to be converted. I will open a PR that will handle this.
> 
> Thanks for the feedback.

Hi,

thanks for the PR. While I looked at it another thing could be @todo as annotation. Maybe that should be converted to Pests todo? I'm not sure but maybe it could be useful.

Thanks for the great work and keep it going :-)

**Pull request merged**
